In [1]:
import pandas as pd

In [2]:
df = pd.read_table("lpmc02.dat")

In [3]:
df.columns, df.shape

(Index(['trip_id', 'household_id', 'person_n', 'trip_n', 'travel_mode',
        'purpose', 'fueltype', 'faretype', 'bus_scale', 'survey_year',
        'travel_year', 'travel_month', 'travel_date', 'day_of_week',
        'start_time', 'age', 'female', 'driving_license', 'car_ownership',
        'distance', 'dur_walking', 'dur_cycling', 'dur_pt_access',
        'dur_pt_rail', 'dur_pt_bus', 'dur_pt_int', 'pt_interchanges',
        'dur_driving', 'cost_transit', 'cost_driving_fuel',
        'cost_driving_ccharge', 'driving_traffic_percent'],
       dtype='object'), (5000, 32))

In [4]:
# 4 strata

S1 = df[(df.age <= 40) & (df.female == 1)]
S2 = df[(df.age > 40) & (df.female == 1)]
S3 = df[(df.age <= 40) & (df.female == 0)]
S4 = df[(df.age > 40) & (df.female == 0)]

strata = {"S1": S1.shape[0], "S2": S2.shape[0], "S3": S3.shape[0], "S4": S4.shape[0]}
popu_est = {"S1": 2599058, "S2": 1765143, "S3": 2676249, "S4": 1633263}

S = sum(list(strata.values()))
N = sum(list(popu_est.values()))

df_sw = pd.DataFrame(columns=list(strata.keys()), index=["Size", "Weight"])
for key,val in strata.items():
    df_sw.at["Size", key] = val
    df_sw.at["Weight", key] = S/val * popu_est[key]/N
    
# associate each weight with an individual n

S1["Weights"] = df_sw.loc["Weight", "S1"]
S2["Weights"] = df_sw.loc["Weight", "S2"]
S3["Weights"] = df_sw.loc["Weight", "S3"]
S4["Weights"] = df_sw.loc["Weight", "S4"]

df_new = pd.concat([S1, S2, S3, S4]).reset_index(drop=True)

/home/hienle/.virtualenvs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/hienle/.virtualenvs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/hienle/.virtualenvs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/hienle/.virtualenvs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [5]:
df_new

,trip_id,household_id,person_n,trip_n,travel_mode,purpose,fueltype,faretype,bus_scale,survey_year,...,dur_pt_rail,dur_pt_bus,dur_pt_int,pt_interchanges,dur_driving,cost_transit,cost_driving_fuel,cost_driving_ccharge,driving_traffic_percent,Weights
0,46487,9923,3,1,3,2,6,3,0.0,2,...,0.000000,0.071111,0.000000,0,0.152778,0.0,0.40,0.0,0.318182,1.070170
1,76528,16553,2,0,3,5,6,4,1.0,3,...,0.416667,0.050000,0.100000,1,0.852500,4.1,2.22,0.0,0.588465,1.070170
2,32857,7078,0,2,4,3,2,1,1.0,2,...,0.000000,0.337500,0.000000,0,0.161667,1.5,0.43,0.0,0.324742,1.070170
3,69198,14953,2,2,4,3,2,5,0.0,3,...,0.000000,0.223333,0.150000,1,0.177222,0.0,0.53,0.0,0.286834,1.070170
4,31416,6767,2,0,1,2,1,5,0.0,2,...,0.000000,0.032500,0.000000,0,0.085000,0.0,0.22,0.0,0.366013,1.070170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43083,9200,0,4,4,3,1,1,1.0,2,...,0.000000,0.160556,0.089444,1,0.198611,3.0,0.46,0.0,0.346853,0.859819
4996,16502,3487,0,1,4,3,2,1,1.0,1,...,0.000000,0.349444,0.000000,0,0.146944,1.5,0.34,0.0,0.100189,0.859819
4997,6328,1296,0,6,4,3,6,1,1.0,1,...,0.000000,0.035833,0.000000,0,0.048333,1.5,0.15,0.0,0.149425,0.859819
4998,26781,5782,0,1,4,4,1,1,1.0,1,...,0.183333,0.307500,0.266667,2,0.645000,5.1,1.81,0.0,0.486219,0.859819
4999,78029,16899,0,0,4,3,1,5,0.0,3,...,0.000000,0.140556,0.000000,0,0.111111,0.0,0.37,0.0,0.187500,0.859819

In [6]:
print(df_sw)

             S1        S2       S3        S4
Size       1400      1224     1281      1095
Weight  1.07017  0.831311  1.20432  0.859819

In [7]:
df_new.to_csv("new_lpmc02.dat", sep="\t")

In [8]:
df_new

,trip_id,household_id,person_n,trip_n,travel_mode,purpose,fueltype,faretype,bus_scale,survey_year,...,dur_pt_rail,dur_pt_bus,dur_pt_int,pt_interchanges,dur_driving,cost_transit,cost_driving_fuel,cost_driving_ccharge,driving_traffic_percent,Weights
0,46487,9923,3,1,3,2,6,3,0.0,2,...,0.000000,0.071111,0.000000,0,0.152778,0.0,0.40,0.0,0.318182,1.070170
1,76528,16553,2,0,3,5,6,4,1.0,3,...,0.416667,0.050000,0.100000,1,0.852500,4.1,2.22,0.0,0.588465,1.070170
2,32857,7078,0,2,4,3,2,1,1.0,2,...,0.000000,0.337500,0.000000,0,0.161667,1.5,0.43,0.0,0.324742,1.070170
3,69198,14953,2,2,4,3,2,5,0.0,3,...,0.000000,0.223333,0.150000,1,0.177222,0.0,0.53,0.0,0.286834,1.070170
4,31416,6767,2,0,1,2,1,5,0.0,2,...,0.000000,0.032500,0.000000,0,0.085000,0.0,0.22,0.0,0.366013,1.070170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43083,9200,0,4,4,3,1,1,1.0,2,...,0.000000,0.160556,0.089444,1,0.198611,3.0,0.46,0.0,0.346853,0.859819
4996,16502,3487,0,1,4,3,2,1,1.0,1,...,0.000000,0.349444,0.000000,0,0.146944,1.5,0.34,0.0,0.100189,0.859819
4997,6328,1296,0,6,4,3,6,1,1.0,1,...,0.000000,0.035833,0.000000,0,0.048333,1.5,0.15,0.0,0.149425,0.859819
4998,26781,5782,0,1,4,4,1,1,1.0,1,...,0.183333,0.307500,0.266667,2,0.645000,5.1,1.81,0.0,0.486219,0.859819
4999,78029,16899,0,0,4,3,1,5,0.0,3,...,0.000000,0.140556,0.000000,0,0.111111,0.0,0.37,0.0,0.187500,0.859819